version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gencrest_db
      POSTGRES_USER: gencrest
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads



volumes:
  postgres_data:
  redis_data: